name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to GitHub page
    env:
      MY_SECRET: ${{secrets.TOKEN}}
      USER_NAME: ycjoyce
      USER_EMAIL: yeechiajoyce@gmail.com
      PUBLISH_DIR: ./dist
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node_version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}
      - name: Install Dependencies
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Set deployment config
        run: |
          cd $PUBLISH_DIR
          git init
          git config --global user.email $USER_EMAIL
          git config --global user.name $USER_NAME
          git status
          git remote add origin git@github.com:ycjoyce/audio-player.git
      - name: Deploy to GitHub page
        run: |
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy"
          git push origin gh-pages -f
          echo ðŸ¤˜ deploy gh-pages complete.
          cd -